name: garbage
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.19
  - pip=24.2
  - cudatoolkit=11.3
  - pytorch=2.4.1
  - torchvision=0.19.1
  - numpy=1.24.4
  - tqdm
  - pip:
    - webdataset==0.2.5
    - torchmetrics==0.6.0
    - matplotlib
    - termcolor
    - pillow
    - git+https://github.com/openai/CLIP.git
    - -e .